### ISSUE TITLE
[BUG] Error during 2.91.0 Load

### ISSUE THREAD

**Issue by ItsNatoriousB** [schroef/Extra-Image-List#4]
**OS:**
 OS X - OS: [e.g. OSX, Windows, Linux]

**ADDON:**
 0.2.3 - Version: [e.g.: Release date or Version]

**Describe the bug**
Error is thrown when running Blender from command line.

Warning: 'extra_image_list.image_list' doesn't contain '_UL_' with prefix & suffix
Warning: class QMM_Preferences contains a property which should be an annotation!

**To Reproduce**
1. Start Blender from terminal
2. Error shows after Blender has loaded.

**Screenshots**

**Comment by schroef** [comment]
Hi @ItsNatoriousB , sorry to get back out you so late. At the moment im without a proper working laptop to check the errors.
Im hoping to get a laptop really soon so i can update my Blender and do some work on this addon again.

Concerning that error. I did see that in my last working Blender version 2.80, 2,81,283 locally as well. Its just warning and the addon should still work.

Could you confirm you do see it in the texture panel or image editor panel?

**Comment by zelfor** [comment]
Hi!

i have this error:

Traceback (most recent call last):
  File "C:\3D Program\Blender\2.91.0\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Extra-Image-List_v0'

![image](https://user-images.githubusercontent.com/8266812/105456712-64a5bb00-5c64-11eb-8bc5-0d5908707c3f.png)

**Comment by ClementeAlDente** [comment]
Hello , I have the exact same error message :


> Hi!
> 
> i have this error:
> 
> Traceback (most recent call last):
> File "C:\3D Program\Blender\2.91.0\2.91\scripts\modules\addon_utils.py", line 351, in enable
> mod = **import**(module_name)
> ModuleNotFoundError: No module named 'Extra-Image-List_v0'
> 
> ![image](https://user-images.githubusercontent.com/8266812/105456712-64a5bb00-5c64-11eb-8bc5-0d5908707c3f.png)

**Comment by schroef** [comment]
@ClementeAlDente @zelfor 

Hi guys, this errors is due to me giving the folder inside the zip a version number. You can fix this error by renaming the folder to `Extra-Image-List' this will make it run properly.

_Renamed folder looks like this_
![rename-folder-extraimagelist](https://user-images.githubusercontent.com/6923008/109438148-fa203180-79fe-11eb-8329-e6f1eb09699c.jpg)


That warning about _UL_ doesnt influence the addon. I will update in a later version. Im thinking of perhaps making the list/icon view also possible in the compositor, but i think i would need to make a custom node for that.

**Comment by schroef** [comment]
Fixed some old stuff and updated it
please try https://github.com/schroef/Extra-Image-List/releases/latest
